### PR TITLE
Fix #540, Fix #573: prevent root perm to become undefined bucket

### LINKED ISSUE #540: Undefined bucket
- `make serve` on kinto 9.1.0
- login to `localhost:8888`
- bucket list is empty but allows me to create a collection
screenshot from 2018-05-22 19-06-09
- Leads to «undefined» bucket 
screenshot from 2018-05-22 19-07-35

### LINKED ISSUE #573: The filter input in the sidebar doesn't work
And it throws an error in the console:

```TypeError: t.id is undefined```

To reproduce: try entering anything in the sidebar's filter input.

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #540 
Fix #573

### CODE REVIEW

File: src/sagas/session.js [hunk 1]
```diff
@@ -147,6 +147,10 @@ export function expandBucketsCollections(
   // Augment the list of bucket and collections with the ones retrieved from
   // the /permissions endpoint
   for (const permission of permissions) {
+    if (!permission.hasOwnProperty("bucket_id")) {
+      // e.g. root permission.
```
Comment (Natim) [inline src/sagas/session.js]: Permission obtained from settings?

**Comment by leplatrem** [comment]
This will also fix #573
