### PR TITLE
Fix #329: better detection of authentication failures

### LINKED ISSUE #329: Clean-up authentication / anonymous management
* Make sure the server authenticates the user
* Make sure the chosen auth method is the one picked by the server (`serverInfo.user.id.startswith(authType)`)
* Go back to login back when auth fails

From:
* https://github.com/Kinto/kinto-admin/pull/327
* https://github.com/Kinto/kinto-admin/pull/328

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #329

When basicauth is enabled (since it accepts everything)

### CODE REVIEW

File: src/sagas/session.js [hunk 1]
```diff
@@ -62,6 +62,21 @@ export function* listBuckets(getState, action) {
     const client = getClient();
     // Fetch server information
     const serverInfo = yield call([client, client.fetchServerInfo]);
+
+    const {user={}} = serverInfo;
+    const {session: {auth: {authType, credentials: {username}}}} = getState();
+    if (authType != "anonymous") {
+      if (user) {
+        const [policy, userId] = user.id.split(":", 1);
+        if (policy !≃ authType) {
```
Comment (n1k0) [inline src/sagas/session.js]: `≃` isn't a supported operator I think

File: test/sagas/session_test.js [hunk 2]
```diff
@@ -20,27 +21,84 @@ const authData = {
...
+        setupSession.next();
+
+        setupSession.next(); // call to fetch server.
+        setupSession.next({
+          ...serverInfo,
+          user: {},
+        });
+
+        expect(setupSession.next().value).eql(
+          put(notifyError("Authentication failed.", "error"))
```
Comment (leplatrem) [inline test/sagas/session_test.js]: This fails. Why?
