### PR TITLE
Fix #625: Show an error message when rjsf component crashes

### LINKED ISSUE #625: Page crash if user sets wrong ui:widget
screenshot from 2018-09-27 18-18-02

It should probably be better to show an error within the UI

### PR DESCRIPTION
**Pull request by alexcottner**
Resolves #625 - Show an error message when rjsf component crashes due to bad config.
Added comments detailing why we're doing things this way and unit test to verify it works as expected.

image

### CODE REVIEW

File: src/components/BaseForm.tsx [hunk 1]
```diff
@@ -37,17 +37,65 @@ export default function BaseForm(props: BaseFormProps) {
...
+  declare props: {
+    children: ReactNode;
+  };
+
+  constructor(props) {
+    super(props);
+    this.state = {};
+  }
+
+  static getDerivedStateFromError(thrown) {
```
Comment (leplatrem) [inline src/components/BaseForm.tsx:77]: I see that this is the key method in this pattern https://react.dev/reference/react/Component#static-getderivedstatefromerror

File: src/components/BaseForm.tsx [hunk 2]
```diff
@@ -37,17 +37,65 @@ export default function BaseForm(props: BaseFormProps) {
...
+  }
+
+  render() {
+    if (this.state.thrown) {
+      return (
+        <>
+          <h2>Error rendering form</h2>
+          <div>
+            This is likely caused by a bad <code>ui:widget</code> value in this
+            collection's UI schema.
```
Comment (leplatrem) [inline src/components/BaseForm.tsx:90]: Should we make this a link so that user can open collection attributes and fix it?

**Review by leplatrem — APPROVED** [review]
👌 

Wrapping the component seems a reasonable pattern.
Ideally #253 could help, but errors in schemas can be introduced via other means than the UI so preventing this is a plus 💯

**Review by grahamalama — APPROVED** [review]

File: src/components/BaseForm.tsx (hunk 2 above)
Comment (alexcottner) [reply src/components/BaseForm.tsx]: Added a parameter for custom error messages, adjusted unit test, and adjusted RecordForm and RecordBulk components to send a link with their custom messages. Good call.
