### PR TITLE
Fix #339: Fix server history not saved.

### LINKED ISSUE #339: Server history dropdown doesn't work anymore
For some strange reason this appears to not work anymore.

/cc @ticabri

### PR DESCRIPTION
**Pull request by n1k0**
r=? @leplatrem

### CODE REVIEW

File: src/sagas/session.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ export function* listBuckets(getState, action) {
     // that the credentials are valid :/
     yield put(sessionActions.setAuthenticated());
     // Store this valid server url in the history
-    yield put(historyActions.addHistory(getState().session.serverInfo.url));
+    yield put(historyActions.addHistory(getState().session.auth.server));
```
Comment (leplatrem) [inline src/sagas/session.js]: Here we could save `serverInfo.url` in the history? (i.e. not the URL entered but the actual one defined by the server, e.g. after redirect etc.)
What do you think?

Comment (n1k0) [inline src/sagas/session.js]: This is what was done before but this can be empty when the session has not received this information just yet.

Now I think about it it should never happen, but that's what I saw in the redux logs... I'll investigate
